notifications:
  email: false
language: generic
before_install:
  - openssl aes-256-cbc -K $encrypted_b46a5d04fea8_key -iv $encrypted_b46a5d04fea8_iv -in rclone.conf.enc -out rclone.conf -d
install:
  - sudo apt-get install -y curl unzip python python-pip
  - sudo add-apt-repository -y ppa:gophers/archive
  - sudo apt-get update
  - sudo apt-get install -y golang-1.9-go
  - export PATH=$PATH:/usr/lib/go-1.9/bin 
  - go get github.com/magefile/mage
  - go get -d github.com/gohugoio/hugo
  - cd ${GOPATH:-$HOME/go}/src/github.com/gohugoio/hugo
  - mage vendor
  - mage install
  - curl https://rclone.org/install.sh | sudo bash
before_script:
  - mkdir -p ~/.config/rclone/
  - cp rclone.conf ~/.config/rclone/rclone.conf
  - chmod 600 ~/.config/rclone/rclone.conf
script:
  - deploy_ceeds.sh
  - echo "hi"
