notifications:
  email: false
language: node_js

jobs:
  stage: deploy
  before_install:
    - openssl aes-256-cbc -K $encrypted_b46a5d04fea8_key -iv $encrypted_b46a5d04fea8_iv -in rclone.conf.enc -out rclone.conf -d
    - sudo apt-get install -y curl unzip python python-pip hugo
    - curl https://rclone.org/install.sh | sudo bash
    - mkdir -p ~/.config/rclone/
    - cp rclone.conf ~/.config/rclone/rclone.conf
    - chmod 600 ~/.config/rclone/rclone.conf
  before_script:
    - deploy_ceeds.sh
    - echo "hi"
