notifications:
  email: false
language: generic
before_install:
  - openssl aes-256-cbc -K $encrypted_b46a5d04fea8_key -iv $encrypted_b46a5d04fea8_iv -in rclone.conf.enc -out rclone.conf -d
install:
  - sudo apt-get install -y curl unzip python python-pip
  - wget https://github.com/gohugoio/hugo/releases/download/v0.37.1/hugo_0.37.1_Linux-64bit.deb
  - sudo dpkg -i *.deb
  - sudo apt-get install -y curl
  - curl https://rclone.org/install.sh | sudo bash
before_script:
  - mkdir -p ~/.config/rclone/
  - sudo cp rclone.conf ~/.config/rclone/.
  - chmod 600 ~/.config/rclone/rclone.conf
script:
  - deploy_ceeds.sh
  - echo "hi"
